projects:
  projectforecaster:
    schemaPath: amplify/backend/api/projectforecaster/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.d.ts
        docsFilePath: src/graphql
        region: us-west-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
